version: 2.1

# To test 2.1 config locally you need to run:
# circleci config process .circleci/config.yml > ci.yml.tmp && circleci local execute -c ci.yml.tmp

jobs:
  test:
    docker:
      - image: technic93/e2xvfb:0.1

    parameters:
      provider:
        type: string
        default: "all"

    environment:
      PROVIDER: << parameters.provider >>

    steps:
      - checkout

      - run:
          name: info
          command: |
            uname -a
            whoami
            echo PROVIDER=${PROVIDER}

      - run:
          name: pep8
          command: |
            echo $PATH |tr ':' '\n'
            sudo pip install pep8
            pep8 --version
            pep8 --ignore E126,E266,E226,W191,W293,E731 --max-line-length=119 src

      - run:
          name: test update
          command: |
            sudo mkdir -p /dev/input
            sudo service apache2 start
            sudo Xvfb :99 -ac -screen 0 1280x720x16 &
            export DISPLAY=:99
            ps ax
            cat src/dist.py
            sudo -E python update-test.py

  build:
    docker:
      - image: technic93/e2xvfb:0.1

    parameters:
      provider:
        type: string
        default: "all"

    environment:
      PROVIDER: << parameters.provider >>

    steps:
    - checkout

    - run:
        name: info
        command: |
          uname -a
          whoami
          echo PROVIDER=${PROVIDER}

    - run:
        name: build
        command: |
          make
          make DEB=y

    - persist_to_workspace:
        root: .
        paths:
        - packages/*

  deploy:
    docker:
      - image: python:2.7.15

    steps:
      - checkout

      - attach_workspace:
          at: packages

      - run:
          name: build and deploy
          # TODO:
          command: |
            apt-get update && apt-get install -y gettext rsync
            ls packages/
            rsync -rt --delay-updates packages/ $UPDATE_SERVER:~/iptvdream4x/packages


default-all: &default-all
  provider: all
  filters:
    branches:
      ignore:
        - cbilling
        - cbilling/*

default-cbilling: &default-cbilling
  provider: cbilling
  filters:
    branches:
      only:
      - cbilling
      - cbilling/*


workflows:
  task-all:
    jobs:
      - test: *default-all
      - build: *default-all

  task-cbilling:
    jobs:
      - test: *default-cbilling
      - build: *default-cbilling
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - cbilling
                - cbilling/*
            tags:
              only: cbilling/v*
